import { Tour, Hotel, BlogPost, SiteContent } from "./types";

export const TOURS_DATA: Tour[] = [
  {
    id: "tour-1",
    title: "Üsküp - Manastır - Resne - Ohrid Turu",
    title_en: "Skopje - Bitola - Resen - Ohrid Balkan Tour",
    image: "https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?q=80&w=800&auto=format&fit=crop",
    price: 350,
    duration: "4 Günlük Tur",
    duration_en: "4-Day Tour",
    location: "Makedonya, Balkanlar",
    location_en: "North Macedonia, Balkans",
    category: "yurt-disi",
    tag: "Kültür Turu",
    tag_en: "Cultural Tour",
    description: "Balkanların kalbi Makedonya'da tarihi ve doğal güzellikleri keşfedin. Üsküp'ün taş köprülerinden, Manastır'daki Atatürk'ün okuduğu Askeri İdadi'ye, Resne'den Ohrid Gölü'nün muazzam manzaralarına uzanan unutulmaz bir deneyim.",
    description_en: "Discover the enchanting history and breathtaking landscapes at the heart of the Balkans. From Skopje's iconic Stone Bridge to the historic military academy in Bitola where Atatürk studied, journey through Resen to the crystal-clear shores of Lake Ohrid.",
    program: "1. Gün: İstanbul Havalimanı buluşma, Üsküp uçuşu, Taş Köprü, Eski Türk Çarşısı, Rahibe Teresa Evi gezisi ve otel konaklaması.\n2. Gün: Tetovo (Kalkandelen) Alaca Cami ziyareti, ardından UNESCO korumalı masalsı Ohrid şehrine hareket ve tekne turu.\n3. Gün: Resne'de Niyazi Bey Sarayı ziyareti, ardından Manastır (Bitola), Atatürk'ün eğitim gördüğü Askeri İdadi Müzesi ve Şirok Sokak gezisi.\n4. Gün: Matka Kanyonu doğa yürüyüşü, serbest alışveriş zamanı ve akşam İstanbul'a dönüş uçuşu.",
    program_en: "Day 1: Flight from Istanbul to Skopje, Stone Bridge walking tour, Old Bazaar, Mother Teresa Memorial House, and hotel check-in.\nDay 2: Visit Tetovo Painted Mosque, scenic drive to UNESCO-listed Ohrid, and optional boat cruise along the lake.\nDay 3: Explore Resen & Niyazi Bey Palace, continue to Bitola to visit the Military Academy where Atatürk studied and Sirok Street.\nDay 4: Morning boat safari at Matka Canyon, souvenir shopping at the bazaar, and return flight to Istanbul.",
    included: "• Gidiş - dönüş tarifeli uçak biletleri ve vergiler\n• 4 yıldızlı seçkin otellerde 3 gece oda kahvaltı konaklama\n• Lüks otobüslerle tüm transferler ve şehir turları\n• Profesyonel Türkçe / İngilizce yerel rehberlik hizmeti\n• Matka Kanyonu ve Ohrid şehir girişleri\n• Zorunlu seyahat sağlık sigortası",
    included_en: "• Roundtrip international flights & airport taxes\n• 3 nights accommodation in 4-star hotels with breakfast\n• Luxury coach transportation for all excursions\n• Professional English & Turkish speaking licensed guides\n• Entrance fees to Matka Canyon and historic sites\n• Mandatory international travel health insurance",
    excluded: "• Kişisel harcamalar ve ekstra otel içi tüketimler\n• Öğle ve akşam yemekleri (Belirtilen yöresel akşam yemekleri hariç)\n• Ohrid Gölü tekne turu opsiyonel biletleri\n• Yurtdışı çıkış harç pulu",
    excluded_en: "• Personal expenses, souvenirs, and minibar usage\n• Lunches and dinners (unless specified in package)\n• Optional Lake Ohrid boat cruise ticket\n• International departure tax stamp",
    departurePoints: "• 06:00 - İstanbul Havalimanı Dış Hatlar Gidiş Terminali Türk Hava Yolları Kontuarı Önü\n• 06:30 - Sabiha Gökçen Havalimanı Dış Hatlar Terminali Buluşma Noktası",
    departurePoints_en: "• 06:00 AM - Istanbul Airport (IST) International Departures Terminal THY Desk\n• 06:30 AM - Sabiha Gokcen Airport (SAW) International Departures Meeting Area",
    tourConditions: "1. Seyahat tarihi itibariyle en az 6 ay geçerli pasaport zorunludur.\n2. Kuzey Makedonya Türk vatandaşlarına 90 güne kadar vizesizdir.\n3. Uçak saatlerindeki olası rötar ve değişiklikler hava yolu firması sorumluluğundadır.\n4. Tur kalkışından 30 gün öncesine kadar yapılan iptallerde kesintisiz ücret iadesi uygulanır.\n5. Rehber, hava ve sınır geçiş şartlarına göre program akışında değişiklik yapabilir.",
    tourConditions_en: "1. Passport must be valid for at least 6 months beyond the date of departure.\n2. North Macedonia is visa-free for Turkish citizens and multiple nationalities.\n3. Flight schedules and delays are subject to airline operational policies.\n4. Cancellations up to 30 days prior to departure qualify for a 100% full refund.\n5. The tour guide reserves the right to modify the sequence of visits according to weather conditions.",
  },
  {
    id: "tour-2",
    title: "Safranbolu - Amasra Turu",
    title_en: "Historic Safranbolu & Black Sea Amasra Tour",
    image: "https://images.unsplash.com/photo-1549419138-51829e29aeb6?q=80&w=800&auto=format&fit=crop",
    price: 150,
    duration: "2 Günlük Tur",
    duration_en: "2-Day Tour",
    location: "Batı Karadeniz, Türkiye",
    location_en: "Western Black Sea, Turkey",
    category: "yurt-ici",
    tag: "Hafta Sonu",
    tag_en: "Weekend Getaway",
    description: "UNESCO Dünya Mirası listesindeki tarihi Safranbolu evlerinin mistik havasını soluyun, ardından Karadeniz'in incisi Amasra'da muhteşem doğa ve deniz manzarasının keyfini çıkarın. Tarih ve doğa iç içe.",
    description_en: "Immerse yourself in the timeless Ottoman charm of UNESCO-listed Safranbolu mansions, followed by the coastal serenity of Amasra, the jewel of the Black Sea. A seamless blend of heritage and coastal nature.",
    program: "1. Gün: İstanbul'dan hareket. Safranbolu'ya varış, Hıdırlık Tepesi panoraması, Kaymakamlar Evi, Cinci Hanı ve Yemeniciler Arastası gezisi. Otele yerleşme ve akşam yemeği.\n2. Gün: Sabah kahvaltısının ardından Kristal Teras ve Tokatlı Kanyonu ziyareti. Fatih Sultan Mehmet'in 'Çeşm-i Cihan' dediği Amasra'ya geçiş, Kemere Köprüsü, Amasra Kalesi ve meşhur Amasra salatası eşliğinde balık ziyafeti. Akşam İstanbul'a dönüş.",
    program_en: "Day 1: Morning departure from Istanbul. Arrive at Safranbolu, panoramic views from Hıdırlık Hill, Governors House Museum, Cinci Han Caravanserai, and Yemeniciler Bazaar. Check-in and dinner.\nDay 2: Tokatlı Canyon & Crystal Glass Terrace, followed by coastal Amasra. Visit Kemere Bridge, Amasra Castle, and enjoy iconic Black Sea fresh fish and traditional Amasra salad. Return to Istanbul.",
    included: "• Lüks tur araçlarıyla gidiş - dönüş ulaşım\n• Tarihi Safranbolu konağında veya 4 yıldızlı otelde 1 gece konaklama\n• 1 sabah kahvaltısı ve 1 akşam yemeği\n• Profesyonel kokartlı rehberlik hizmeti\n• Kristal Teras ve Tokatlı Kanyonu giriş ücretleri\n• Araç içi ikramlar ve seyahat sigortası",
    included_en: "• Roundtrip transportation via modern luxury coach\n• 1 night boutique mansion/hotel accommodation\n• 1 buffet breakfast and 1 traditional dinner\n• Professional Ministry-licensed guide\n• Entrance fees to Tokatlı Canyon & Crystal Terrace\n• Complimentary onboard refreshments and travel insurance",
    excluded: "• İlk gün sabah kahvaltısı ve tüm öğle yemekleri\n• Amasra tekne turu biletleri (isteğe bağlı)\n• Kişisel harcamalar ve lokum alışverişleri",
    excluded_en: "• Day 1 breakfast and all lunch stops\n• Optional coastal boat tour in Amasra\n• Personal expenses and local Turkish delight shopping",
    departurePoints: "• 06:30 - Bakırköy İncirli Doğtaş Mobilya Önü\n• 07:00 - Mecidiyeköy Torun Center Önü\n• 07:30 - Kadıköy Evlendirme Dairesi Otoparkı\n• 08:00 - Kartal Köprüsü Otobüs Durağı",
    departurePoints_en: "• 06:30 AM - Bakırköy İncirli Metro Station Exit\n• 07:00 AM - Mecidiyeköy Torun Center Main Gate\n• 07:30 AM - Kadıköy Marriage Office Parking Lot\n• 08:00 AM - Kartal Bridge Highway Bus Stop",
    tourConditions: "1. Tur kalkış saatinden 15 dakika önce buluşma noktasında olunmalıdır.\n2. Koltuk numaraları rezervasyon sırasına göre belirlenmektedir.\n3. İptal talepleri tur tarihinden 7 gün öncesine kadar kesintisiz karşılanır.\n4. Yürüyüşe uygun spor ayakkabı giyilmesi tavsiye edilir.",
    tourConditions_en: "1. Please arrive at your selected departure point 15 minutes prior to scheduled departure.\n2. Seat allocations are made automatically upon booking confirmation.\n3. Cancellations submitted at least 7 days before departure receive a 100% refund.\n4. Comfortable walking shoes are strongly recommended.",
  },
  {
    id: "tour-3",
    title: "Günübirlik Ankara Ziyareti",
    title_en: "Day Trip to Capital Ankara & Heritage Sites",
    image: "https://images.unsplash.com/photo-1588725845946-b2dcb4a9eb4c?q=80&w=800&auto=format&fit=crop",
    price: 80,
    duration: "Günübirlik Tur",
    duration_en: "Full-Day Tour",
    location: "Ankara, Türkiye",
    location_en: "Ankara, Turkey",
    category: "yurt-ici",
    tag: "Kültür Turu",
    tag_en: "Cultural Tour",
    description: "Cumhuriyetimizin başkenti Ankara'ya günübirlik hızlı ve konforlu bir gezi. Anıtkabir ziyareti, Birinci Meclis, Ankara Kalesi ve Anadolu Medeniyetleri Müzesi ile tarihe doyacağınız bir gün sizleri bekliyor.",
    description_en: "Experience the rich heritage of Turkey's capital city. Highlights include Anıtkabir (the Mausoleum of Atatürk), the First Grand National Assembly, historic Ankara Castle, and the world-renowned Museum of Anatolian Civilizations.",
    program: "• 06:00: İstanbul'dan hareket ve araç içi kahvaltı paketi ikramı.\n• 10:30: Ankara'ya varış ve Anıtkabir ziyareti (Aslanlı Yol, Atatürk Müzesi ve mozole saygı duruşu).\n• 13:00: Ulus Meydanı, 1. ve 2. TBMM Kurtuluş Savaşı Müzesi gezisi.\n• 14:30: Meşhur Ankara tava eşliğinde öğle yemeği molası.\n• 15:45: Anadolu Medeniyetleri Müzesi ve tarihi Ankara Kalesi panoramasının görülmesi.\n• 18:30: İstanbul'a dönüş hareketi ve 22:30 civarı varış.",
    program_en: "• 06:00 AM: Departure from Istanbul with onboard light breakfast.\n• 10:30 AM: Arrival at Anıtkabir (Lion Road, Atatürk Museum, and Mausoleum visit).\n• 01:00 PM: Ulus Square, 1st & 2nd Turkish Grand National Assembly Museums.\n• 02:30 PM: Traditional lunch stop with authentic Ankara specialties.\n• 03:45 PM: Museum of Anatolian Civilizations and Ankara Citadel panoramic viewpoint.\n• 06:30 PM: Return drive to Istanbul, arriving around 10:30 PM.",
    included: "• Lüks tur otobüsü ile gidiş - dönüş ulaşım\n• Araç içi kahvaltı paketi ve gün boyu sıcak / soğuk ikramlar\n• Profesyonel rehberlik hizmeti\n• Müze giriş rezervasyonları ve seyahat sigortası",
    included_en: "• Roundtrip luxury coach transportation\n• Onboard light breakfast box and beverages\n• Professional Ministry of Tourism licensed guide\n• Travel insurance and tour logistics",
    excluded: "• Öğle yemeği ve kişisel harcamalar\n• MüzeKart kapsamı dışındaki ekstra müze biletleri",
    excluded_en: "• Lunch and personal souvenir expenses\n• Extra museum entries not included in MüzeKart",
    departurePoints: "• 05:45 - Bakırköy İncirli Doğtaş Mobilya Önü\n• 06:15 - Mecidiyeköy Torun Center Önü\n• 06:45 - Kadıköy Evlendirme Dairesi Otoparkı\n• 07:15 - Pendik Köprüsü Altı",
    departurePoints_en: "• 05:45 AM - Bakırköy İncirli Metro Station\n• 06:15 AM - Mecidiyeköy Torun Center\n• 06:45 AM - Kadıköy Marriage Office Parking Lot\n• 07:15 AM - Pendik Highway Junction",
    tourConditions: "1. Anıtkabir ziyaretinde resmi kıyafet kurallarına ve güvenlik protokollerine uyulmalıdır.\n2. Tur günü kimlik kartı veya pasaport bulundurulması zorunludur.\n3. 48 saat öncesine kadar kesintisiz iptal hakkı vardır.",
    tourConditions_en: "1. Visitors to Anıtkabir must adhere to official security and memorial protocols.\n2. Valid government ID or passport is mandatory on tour day.\n3. Free cancellation up to 48 hours before departure.",
  },
  {
    id: "tour-4",
    title: "Karadeniz - Batum Turu",
    title_en: "Highlands of Black Sea & Batumi Expedition",
    image: "https://images.unsplash.com/photo-1520114008272-38eb7636e788?q=80&w=800&auto=format&fit=crop",
    price: 450,
    duration: "6 Günlük Tur",
    duration_en: "6-Day Tour",
    location: "Karadeniz ve Gürcistan",
    location_en: "Black Sea & Georgia",
    category: "yurt-disi",
    tag: "Doğa Turu",
    tag_en: "Nature Expedition",
    description: "Yemyeşil yaylalar, hırçın dereler ve muhteşem Karadeniz doğasını doya doya yaşayın. Rize, Trabzon ve Artvin'in ardından sınır ötesine geçerek Batum'un modern ve tarihi mimarisini keşfedin.",
    description_en: "Explore lush green plateaus, cascading waterfalls, and misty alpine valleys across Trabzon, Rize, and Artvin. Continue across the border to Batumi, Georgia, to experience its vibrant seaside promenade and architectural marvels.",
    program: "1. Gün: Trabzon'a varış, Atatürk Köşkü ve Ayasofya Camii gezisi, Uzungöl'e hareket ve konaklama.\n2. Gün: Fırtına Vadisi doğa turu, Zilkale, Palovit Şelalesi ve Ayder Yaylası'na çıkış.\n3. Gün: Borçka Karagöl Tabiat Parkı, Artvin Çoruh Kanyonu ve Gürcistan sınırına geçiş.\n4. Gün: Batum şehir turu: Ali & Nino Heykeli, Piazza Meydanı, Alfabe Kulesi ve Botanik Parkı.\n5. Gün: Rize bezi atölyeleri, Sürmene bıçak atölyeleri ve yöresel çay fabrikası ziyareti.\n6. Gün: Sümela Manastırı ziyareti, Trabzon tereyağı alışverişi ve akşam uçuşuyla dönüş.",
    program_en: "Day 1: Arrival in Trabzon, Atatürk Pavilion, Hagia Sophia Mosque, transfer to Uzungol.\nDay 2: Fırtına Valley safari, Zil Castle, Palovit Waterfall, and Ayder Highland plateau.\nDay 3: Borçka Karagöl Lake Nature Park, Çoruh River canyon, cross border into Georgia.\nDay 4: Full-day Batumi exploration: Ali & Nino moving statue, Piazza, Alphabet Tower, Botanical Garden.\nDay 5: Rize artisan weaving, Sürmene handcrafted knives, and organic tea factory experience.\nDay 6: Sumela Monastery cliffside tour, local regional shopping, and flight back to Istanbul.",
    included: "• Gidiş - dönüş tarifeli uçak biletleri\n• 5 gece seçkin yayla ve şehir otellerinde konaklama\n• 5 açık büfe sabah kahvaltısı ve 4 akşam yemeği\n• Yayla minibüs transferleri ve doğa safarileri\n• Profesyonel Türkçe & İngilizce rehberlik hizmeti\n• Seyahat sağlık ve güvence sigortası",
    included_en: "• Roundtrip scheduled domestic flight tickets\n• 5 nights accommodation in boutique alpine & city hotels\n• 5 buffet breakfasts and 4 dinners\n• Highland 4x4 transfers and national park shuttles\n• Professional licensed guides\n• Full travel insurance package",
    excluded: "• Gürcistan yurt dışı çıkış harcı (500 TL)\n• Tüm öğle yemekleri ve serbest zaman harcamaları\n• Zipline ve rafting gibi ekstrem aktiviteler",
    excluded_en: "• Georgia cross-border departure stamp fee\n• Lunches and personal beverages during meals\n• Optional adventure activities (zipline, rafting)",
    departurePoints: "• 07:00 - İstanbul Havalimanı İç Hatlar Gidiş Terminali\n• 07:30 - Sabiha Gökçen Havalimanı İç Hatlar Terminali",
    departurePoints_en: "• 07:00 AM - Istanbul Airport (IST) Domestic Terminal\n• 07:30 AM - Sabiha Gokcen Airport (SAW) Domestic Terminal",
    tourConditions: "1. Batum geçişi için yeni çipli TC kimlik kartı veya pasaport gereklidir.\n2. Yaylalarda hava değişken olduğundan mont ve yağmurluk bulundurulmalıdır.\n3. 15 gün öncesine kadar ücretsiz iptal güvencesi sunulmaktadır.",
    tourConditions_en: "1. Valid biometric ID card or passport required for entering Batumi, Georgia.\n2. Warm windbreakers and raincoats are essential for alpine highlands.\n3. Free cancellation guaranteed up to 15 days before departure.",
  },
  {
    id: "tour-5",
    title: "Kapadokya Turu",
    title_en: "Magical Cappadocia Hot Air Balloon Journey",
    image: "https://images.unsplash.com/photo-1641128324972-af3212f0f6bd?q=80&w=800&auto=format&fit=crop",
    price: 250,
    duration: "3 Günlük Tur",
    duration_en: "3-Day Tour",
    location: "Nevşehir, Türkiye",
    location_en: "Nevsehir, Turkey",
    category: "yurt-ici",
    tag: "Kültür Turu",
    tag_en: "Iconic Culture",
    description: "Peri bacalarının masalsı dünyasında kaybolun. Gündoğumunda sıcak hava balonlarıyla gökyüzünde süzülme şansı, yeraltı şehirleri, çanak çömlek atölyeleri ve yöresel lezzetlerle dolu büyüleyici bir rota.",
    description_en: "Lose yourself in the fairy-tale landscapes of Cappadocia. Watch sunrise hot air balloons float over fairy chimneys, explore ancient subterranean cities, and discover traditional pottery workshops in Avanos.",
    program: "1. Gün: Nevşehir veya Kayseri Havalimanı karşılama. Göreme Açık Hava Müzesi, Paşabağı Rahipler Vadisi, Devrent Hayal Vadisi ve kaya otelde konaklama.\n2. Gün: Sabah 05:30 gün doğumu sıcak hava balonu turu veya vadi seyri. Uçhisar Kalesi, Kaymaklı Yeraltı Şehri, Avanos Kızılırmak kenarı ve çömlek yapım atölyesi. Akşam dileyenlere geleneksel Türk Gecesi.\n3. Gün: Güvercinlik Vadisi doğa yürüyüşü, Aşk Vadisi fotoğraf molası, yöresel şarap tadımı ve dönüş transferi.",
    program_en: "Day 1: Airport pickup in Nevşehir/Kayseri. Goreme Open Air Museum, Pasabag Monks Valley, Devrent Imagination Valley, and cave hotel check-in.\nDay 2: Optional 05:30 AM sunrise hot air balloon flight. Uchisar Castle panorama, Kaymakli Underground City, Avanos terracotta pottery masterclass, and traditional Turkish Night.\nDay 3: Pigeon Valley hiking, Love Valley photo panorama, authentic wine tasting, and airport transfer.",
    included: "• 2 gece otantik mağara (cave) veya 4 yıldızlı otelde konaklama\n• 2 açık büfe sabah kahvaltısı ve 2 akşam yemeği\n• Lüks araçlarla tüm transfer ve rehberli vadi gezileri\n• Profesyonel Kapadokya bölge rehberliği\n• Çömlek atölyesi gösterisi ve seyahat sigortası",
    included_en: "• 2 nights accommodation in authentic Cave Suite or 4-star hotel\n• 2 buffet breakfasts and 2 dinners\n• Luxury Mercedes Sprinter / coach transportation\n• Professional English & Turkish speaking licensed guide\n• Pottery demonstration and comprehensive travel insurance",
    excluded: "• Sıcak hava balonu uçuş bileti (isteğe bağlı opsiyonel rezervasyon)\n• ATV safari ve atlı safari aktiviteleri\n• Müze giriş kartı / biletleri ve öğle yemekleri",
    excluded_en: "• Hot air balloon flight ticket (optional add-on)\n• ATV quad safari or horseback sunset ride\n• Museum entries and personal beverages at lunch",
    departurePoints: "• 06:00 - İstanbul Havalimanı THY Kontuarı\n• 06:45 - Sabiha Gökçen Havalimanı Pegasus / Ajet Kapısı\n• 09:30 - Kayseri & Nevşehir Havalimanı Karşılama Noktası",
    departurePoints_en: "• 06:00 AM - Istanbul Airport (IST) Domestic Check-in\n• 06:45 AM - Sabiha Gokcen Airport (SAW) Terminal\n• 09:30 AM - Kayseri (ASR) & Nevşehir (NAV) Airport Gate",
    tourConditions: "1. Sıcak hava balonu uçuşları Sivil Havacılık ve hava durumu onayına bağlıdır.\n2. Mağara otel odaları doğal kaya yapısı gereği birbirinden farklı mimariye sahiptir.\n3. Tur kalkışından 7 gün öncesine kadar ücretsiz iptal edilebilir.",
    tourConditions_en: "1. Hot air balloon flights are strictly weather-dependent and subject to Civil Aviation authority clearance.\n2. Cave rooms have unique natural layouts as sculpted into volcanic tuff.\n3. 100% free cancellation up to 7 days prior to travel date.",
  },
  {
    id: "tour-6",
    title: "Kuşadası - Pamukkale Turu",
    title_en: "Ephesus Ruins & Pamukkale Thermal Terraces",
    image: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?q=80&w=800&auto=format&fit=crop",
    price: 220,
    duration: "3 Günlük Tur",
    duration_en: "3-Day Tour",
    location: "Ege Bölgesi, Türkiye",
    location_en: "Aegean Region, Turkey",
    category: "yurt-ici",
    tag: "Kültür & Doğa",
    tag_en: "Heritage & Nature",
    description: "Ege'nin serin sularından Pamukkale'nin bembeyaz travertenlerine uzanan keyifli bir yolculuk. Efes Antik Kenti'nin tarihi atmosferini soluyup, Hierapolis'in şifalı termal sularında yenileneceksiniz.",
    description_en: "Journey through the ancient marvels of Ephesus to the snow-white travertine terraces of Pamukkale. Swim in the mineral-rich thermal waters of Cleopatra's Pool and wander the ancient streets of Hierapolis.",
    program: "1. Gün: İzmir'e varış, Şirince Köyü ziyareti, şarap tadımı, Meryem Ana Evi ve Kuşadası otelimize yerleşme.\n2. Gün: UNESCO Dünya Mirası Efes Antik Kenti (Celsus Kütüphanesi, Antik Tiyatro), Artemis Tapınağı ve Kuşadası kordon serbest zamanı.\n3. Gün: Denizli Pamukkale'ye hareket. Bembeyaz travertenler, Hierapolis Antik Kenti, Kleopatra Antik Termal Havuzu ve dönüş yolculuğu.",
    program_en: "Day 1: Arrival in Izmir, stroll through historic Sirince Village, House of Virgin Mary, and hotel check-in at Kusadasi.\nDay 2: UNESCO Ephesus archaeological park (Library of Celsus, Great Amphitheater), Temple of Artemis, and Kusadasi seaside.\nDay 3: Transfer to Pamukkale, walk on white calcium travertines, Hierapolis necropolis, Cleopatra thermal pool, and return.",
    included: "• 2 gece 4-5 yıldızlı resort otellerde yarım pansiyon konaklama\n• 2 açık büfe sabah kahvaltısı ve 2 akşam yemeği\n• Klimalı konforlu tur araçlarıyla tüm seyahat\n• Profesyonel kokartlı turizm rehberi\n• Seyahat güvence sigortası",
    included_en: "• 2 nights in 4/5-star thermal resort hotels on half-board\n• 2 buffet breakfasts and 2 dinners\n• Modern air-conditioned motorcoach transport\n• Licensed expert English & Turkish tour guide\n• Travel insurance coverage",
    excluded: "• Öğle yemekleri ve içecekler\n• Kleopatra Havuzu yüzme ücreti (isteğe bağlı)\n• Kişisel harcamalar ve bahşişler",
    excluded_en: "• Lunches and private beverages\n• Cleopatra Antique Pool swimming ticket\n• Personal expenses and driver/guide gratuities",
    departurePoints: "• 06:30 - Bakırköy İncirli\n• 07:00 - Mecidiyeköy Torun Center\n• 07:30 - Kadıköy Evlendirme Dairesi\n• 08:30 - Bursa Otogar Buluşma Noktası",
    departurePoints_en: "• 06:30 AM - Bakırköy İncirli Metro\n• 07:00 AM - Mecidiyeköy Torun Center\n• 07:30 AM - Kadıköy Marriage Office\n• 08:30 AM - Bursa Intercity Bus Station",
    tourConditions: "1. Travertenlerde yürümek için ayakkabılar çıkarılmaktadır; çorap veya terlik bulundurabilirsiniz.\n2. Müzekart sahipleri Efes ve Hierapolis girişlerinden ücretsiz yararlanır.\n3. 10 gün öncesine kadar ücretsiz iptal imkanı sağlanır.",
    tourConditions_en: "1. Shoes are removed on travertines to protect mineral terraces; bring socks or water shoes.\n2. Museum Pass holders enjoy free entry to Ephesus and Hierapolis.\n3. Free cancellation up to 10 days before departure.",
  },
  {
    id: "tour-7",
    title: "Büyük GAP Turu",
    title_en: "Grand Mesopotamia & Southeastern Anatolia Tour",
    image: "https://images.unsplash.com/photo-1627914972173-89868fb8a4bc?q=80&w=800&auto=format&fit=crop",
    price: 550,
    duration: "7 Günlük Tur",
    duration_en: "7-Day Tour",
    location: "Güneydoğu Anadolu, Türkiye",
    location_en: "Southeastern Anatolia, Turkey",
    category: "yurt-ici",
    tag: "Kültür Turu",
    tag_en: "Grand Culture",
    description: "Tarihin sıfır noktası Göbeklitepe, Mardin'in dar taş sokakları, Halfeti'nin sular altındaki gizemi ve Gaziantep'in eşsiz lezzetleriyle Mezopotamya'nın kalbine destansı bir yolculuk.",
    description_en: "An epic journey into the cradle of civilizations. Stand at humanity's ground zero at Göbeklitepe, stroll the honey-colored stone alleys of Mardin, sail the sunken village of Halfeti, and savor world-famous Gaziantep gastronomy.",
    program: "1. Gün: Gaziantep'e varış, Zeugma Mozaik Müzesi, Bakırcılar Çarşısı ve Tahmis Kahvesi.\n2. Gün: Şanlıurfa'ya hareket, Fırat Nehri üzerinde Halfeti tekne turu, Balıklıgöl ve Hz. İbrahim Mağarası. Akşam Sıra Gecesi.\n3. Gün: 12.000 yıllık tarihin sıfır noktası Göbeklitepe ve Karahantepe ziyareti, Harran konik evleri.\n4. Gün: Mardin'e varış, Deyrulzafaran Manastırı, Kasımiye Medresesi ve Eski Mardin sokakları.\n5. Gün: Midyat Sıla Konağı, Mor Gabriel Manastırı, Hasankeyf panoramasının görülmesi.\n6. Gün: Diyarbakır Surları, Hevsel Bahçeleri, On Gözlü Köprü ve Cahit Sıtkı Tarancı Müzesi.\n7. Gün: Adıyaman Nemrut Dağı gün doğumu, dev kral heykelleri ve İstanbul'a dönüş uçuşu.",
    program_en: "Day 1: Arrival in Gaziantep, Zeugma Mosaic Museum, Coppersmiths Bazaar, and historic Tahmis Coffeehouse.\nDay 2: Transfer to Sanliurfa, sunken village boat tour in Halfeti, Balikligol Holy Pool, and traditional Sira Night.\nDay 3: Ground zero of human civilization at Gobeklitepe & Karahantepe, Harran beehive adobe houses.\nDay 4: Stroll Old Mardin stone alleys, Deyrulzafaran Saffron Monastery, and Kasimiye Madrasah.\nDay 5: Midyat silverware craftsmen, Mor Gabriel Monastery, and ancient cliffside Hasankeyf.\nDay 6: Diyarbakir UNESCO City Walls, Hevsel Gardens, and historic Ten-Eyed Bridge.\nDay 7: Mount Nemrut sunrise summit among colossal stone deities, and return flight to Istanbul.",
    included: "• Gidiş - dönüş uçak biletleri ve havaalanı vergileri\n• 6 gece 4-5 yıldızlı otellerde oda & kahvaltı konaklama\n• Tüm şehirlerarası lüks otobüs ulaşımı\n• Halfeti tekne turu biletleri\n• Profesyonel GAP uzmanı rehberlik hizmeti\n• Seyahat sağlık sigortası",
    included_en: "• Roundtrip domestic flight tickets\n• 6 nights in 4/5-star regional hotels with breakfast\n• Luxury coach transfers across all cities\n• Halfeti Euphrates River boat excursion\n• Specialized regional guide accompaniment\n• Full travel insurance policy",
    excluded: "• Şanlıurfa Geleneksel Sıra Gecesi (yemekli opsiyonel etkinlik)\n• Tüm öğle ve akşam yemekleri\n• Nemrut Dağı minibüs transferleri",
    excluded_en: "• Traditional Sanliurfa Sira Night cultural dinner\n• Lunches, dinners, and personal beverages\n• Mount Nemrut mountain shuttle fare",
    departurePoints: "• 06:00 - İstanbul Havalimanı İç Hatlar Terminali\n• 06:30 - Sabiha Gökçen Havalimanı İç Hatlar Terminali",
    departurePoints_en: "• 06:00 AM - Istanbul Airport (IST) Domestic Terminal\n• 06:30 AM - Sabiha Gokcen Airport (SAW) Domestic Terminal",
    tourConditions: "1. Mezopotamya yaz aylarında sıcak olduğundan şapka, güneş kremi ve pamuklu giysiler önerilir.\n2. Nemrut Dağı zirvesinde hava serin olduğundan kalın ceket bulundurulmalıdır.\n3. 15 gün öncesine kadar kesintisiz iptal hakkı geçerlidir.",
    tourConditions_en: "1. Sun hat, sunscreen, and breathable cotton clothing recommended for sunny conditions.\n2. Warm jacket essential for Mount Nemrut summit sunrise.\n3. Full 100% refund for cancellations made 15+ days prior to departure.",
  },
  {
    id: "tour-8",
    title: "Kanyonlar Turu",
    title_en: "Wild Canyons & Outdoor Adventure Tour",
    image: "https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?q=80&w=800&auto=format&fit=crop",
    price: 280,
    duration: "4 Günlük Tur",
    duration_en: "4-Day Tour",
    location: "Türkiye",
    location_en: "Turkey",
    category: "yurt-ici",
    tag: "Macera",
    tag_en: "Adventure",
    description: "Doğanın binlerce yılda şekillendirdiği muazzam kanyonları keşfetme vakti. Rafting, doğa yürüyüşleri ve fotoğraf tutkunları için eşsiz manzaralar sunan, adrenalin ve huzur dolu bir macera.",
    description_en: "Hike through awe-inspiring geological gorges carved over millennia. Featuring white-water rafting, guided nature trekking, and panoramic photo opportunities, this tour delivers pure adrenaline and serene wilderness.",
    program: "1. Gün: Antalya'ya varış, Köprülü Kanyon Milli Parkı'na transfer, brifing ve doğa yürüyüşü.\n2. Gün: Köprüçay üzerinde profesyonel rehberler eşliğinde 14 km heyecan dolu rafting macerası ve nehir kenarında ızgara öğle yemeği.\n3. Gün: Tazı Kanyonu'nun 400 metrelik devasa uçurum manzarasında fotoğraf molası, Selge Antik Kenti ve Adam Kayalar keşfi.\n4. Gün: Göynük Kanyonu kanyon geçişi, zipline ve serin sularında yüzme molası. Akşam dönüş.",
    program_en: "Day 1: Arrival in Antalya, transfer to Koprulu Canyon National Park, briefing, and nature trek.\nDay 2: 14 km white-water rafting expedition along the turquoise Koprucay River, riverside barbecue lunch.\nDay 3: Tazi Canyon cliffside viewpoint (400m drop), Selge Ancient City ruins, and bizarre fairy stone formations.\nDay 4: Goynuk Canyon gorge trekking, ziplining, natural pool swimming, and return departure.",
    included: "• 3 gece butik kanyon oteli veya nehir kıyısı bungalov konaklaması\n• 3 kahvaltı ve 2 nehir kenarı öğle yemeği\n• Tam donanımlı rafting ekipmanları (kask, can yeleği, kürek)\n• Profesyonel kanyon rehberleri ve eğitmenleri\n• Özel macera sigortası",
    included_en: "• 3 nights boutique riverside bungalow / hotel stay\n• 3 breakfasts and 2 riverside lunches\n• Full rafting gear (helmet, life vest, paddle)\n• Professional licensed rafting instructors & wilderness guides\n• Adventure sports medical coverage insurance",
    excluded: "• Rafting aksiyon fotoğraf ve video çekimleri\n• Ekstra zipline ücretleri\n• Akşam yemekleri ve özel içecekler",
    excluded_en: "• Professional action photos & GoPro video recordings\n• Optional extra zipline rides\n• Dinners and private alcoholic beverages",
    departurePoints: "• 06:30 - Antalya Havalimanı Buluşma Noktası\n• 07:00 - Antalya Otogar Çıkışı\n• 07:30 - Alanya & Manavgat Otelleri Transfer Noktası",
    departurePoints_en: "• 06:30 AM - Antalya Airport (AYT) Arrivals Hall\n• 07:00 AM - Antalya Intercity Bus Terminal\n• 07:30 AM - Alanya & Manavgat Hotel Pickup Zone",
    tourConditions: "1. Rafting için yüzme bilmek avantaj sağlar ancak can yeleği zorunludur.\n2. Suya dayanıklı ayakkabı veya spor sandalet giyilmesi zorunludur.\n3. 7 gün öncesine kadar ücretsiz iptal hakkı tanınır.",
    tourConditions_en: "1. Life vests provided and mandatory for all participants.\n2. Secure water shoes or strapped sports sandals required.\n3. Full cancellation refund available up to 7 days prior to trip.",
  },
  {
    id: "tour-9",
    title: "Doğu Ekspresi",
    title_en: "Eastern Express Legendary Winter Railway",
    image: "https://images.unsplash.com/photo-1496350325992-95f26941584c?q=80&w=800&auto=format&fit=crop",
    price: 380,
    duration: "5 Günlük Tur",
    duration_en: "5-Day Tour",
    location: "Ankara - Kars, Türkiye",
    location_en: "Ankara - Kars, Turkey",
    category: "yurt-ici",
    tag: "Tren Turu",
    tag_en: "Scenic Train",
    description: "Anadolu'nun büyüleyici kış manzaraları eşliğinde nostaljik bir tren yolculuğu. Kar altındaki doğa harikalarını izleyerek Kars'a uzanan, Çıldır Gölü ve Ani Harabeleri ile taçlanan masalsı bir deneyim.",
    description_en: "Embark on Turkey's most iconic railway route across snow-blanketed Anatolian plateaus. Arrive in Kars to experience horse-drawn sleigh rides across frozen Lake Çıldır and the ancient ghost city of Ani.",
    program: "1. Gün: Ankara Tarihi Tren Garı'nda buluşma, Turistik Doğu Ekspresi yataklı kompartımanlarına yerleşme ve hareket.\n2. Gün: İliç ve Erzincan duraklarında uzun molalar: Kemaliye Karanlık Kanyon ve Ergan Dağı manzaraları.\n3. Gün: Erzurum durağında meşhur Cağ kebabı molası, Çifte Minareli Medrese. Akşam Kars'a varış ve otele yerleşme.\n4. Gün: UNESCO Dünya Mirası Ani Ören Yeri gezisi (Katedral, Menûçihr Camii). Ardından buz tutmuş Çıldır Gölü üzerinde atlı kızak keyfi ve sarıbalık ziyafeti.\n5. Gün: Kars Kalesi, Baltık mimarisi taş binalar, Kars kaşarı ve gravyer peyniri alışverişi sonrası Kars Havalimanı'ndan dönüş uçuşu.",
    program_en: "Day 1: Meet at Ankara Heritage Railway Station, board private sleeping car compartments on the Tourist Eastern Express.\nDay 2: Scenic stops at Ilic and Erzincan: Dark Canyon overview and snow-covered Anatolian ranges.\nDay 3: Extended stop in Erzurum for authentic Cag Kebab and Seljuk twin minarets. Evening arrival in Kars.\nDay 4: UNESCO Ani archaeological ghost city on the Armenian border, followed by frozen Lake Çıldır horse sleigh rides.\nDay 5: Kars Citadel, Russian Baltic-style stone mansions, local aged Gruyere cheese shopping, and evening return flight.",
    included: "• Turistik Doğu Ekspresi Yataklı Vagon bileti (2 kişilik özel kompartıman)\n• Kars'ta 4 yıldızlı otelde 2 gece konaklama\n• Tüm transferler ve profesyonel rehberlik hizmeti\n• Kars - İstanbul dönüş uçak bileti\n• Ani Ören Yeri ve Çıldır Gölü turları\n• Seyahat sağlık sigortası",
    included_en: "• Tourist Eastern Express 1st class sleeping compartment (2-person private berth)\n• 2 nights accommodation in 4-star boutique hotel in Kars\n• Return flight ticket from Kars to Istanbul\n• Fully guided excursions to Ani ruins and Lake Cildir\n• Comprehensive travel health insurance",
    excluded: "• Trende alınan yemekler ve içecekler\n• Çıldır Gölü atlı kızak gezisi (isteğe bağlı)\n• Kişisel harcamalar ve peynir alışverişleri",
    excluded_en: "• Dining car meals and personal beverages aboard train\n• Optional horse-drawn sleigh ride on frozen lake\n• Personal purchases and regional cheese souvenirs",
    departurePoints: "• 14:00 - Ankara Tarihi Tren Garı Ana Giriş Kapısı\n• 10:00 - İstanbul Söğütlüçeşme YHT Garı (Ankara aktarmalı misafirler için)",
    departurePoints_en: "• 02:00 PM - Ankara Historic Central Train Station Main Hall\n• 10:00 AM - Istanbul Sogutlucesme High-Speed Train Station",
    tourConditions: "1. Yataklı vagonda priz, buzdolabı ve lavabo mevcuttur; odalar 2 kişiliktir.\n2. Kış şartları nedeniyle termal içlik, kar botu ve kalın eldiven zorunludur.\n3. Tren biletleri kişiye özel düzenlendiğinden kalkışa 30 gün kala kesinleşir.",
    tourConditions_en: "1. Sleeping cars include private sink, mini-fridge, and 220V power outlets; berths sleep 2 guests.\n2. Thermal base layers, winter snow boots, and gloves are strictly required.\n3. Non-refundable within 30 days of travel date due to state railway regulations.",
  },
  {
    id: "tour-10",
    title: "Doğu Turu",
    title_en: "Eastern Anatolia & Lake Van Discovery",
    image: "https://images.unsplash.com/photo-1580227568551-ceb9706fc867?q=80&w=800&auto=format&fit=crop",
    price: 490,
    duration: "6 Günlük Tur",
    duration_en: "6-Day Tour",
    location: "Doğu Anadolu, Türkiye",
    location_en: "Eastern Anatolia, Turkey",
    category: "yurt-ici",
    tag: "Kültür Turu",
    tag_en: "Cultural Exploration",
    description: "Doğu'nun gizemli ve görkemli atmosferini keşfedin. Erzurum'un tarihi yapıları, İshak Paşa Sarayı'nın muhteşem mimarisi, Van Gölü'nün maviliği ve Akdamar Adası'nın tarihi dokusu sizi bekliyor.",
    description_en: "Uncover the majestic heritage of Eastern Anatolia. Marvel at the cliffside silhouette of Ishak Pasha Palace, the turquoise expanse of Lake Van, the medieval Armenian church on Akdamar Island, and Erzurum's Seljuk architecture.",
    program: "1. Gün: Erzurum'a varış, Çifte Minareli Medrese, Yakutiye Medresesi, Erzurum Kalesi ve cağ kebabı molası.\n2. Gün: Kars ve Sarıkamış üzerinden Doğubayazıt'a geçiş, Ağrı Dağı manzarası eşliğinde görkemli İshak Paşa Sarayı ziyareti.\n3. Gün: Muradiye Şelalesi, Van Kalesi, Urartu Krallığı kalıntıları ve Van Kedisi Evi ziyareti.\n4. Gün: Van Gölü üzerinde tekne turu ile Akdamar Adası'na geçiş, 10. yüzyıl Kutsal Haç Kilisesi ve badem ağaçları manzarası.\n5. Gün: Ahlat Selçuklu Mezarlığı, Nemrut Krater Gölü panoraması ve Bitlis Kalesi.\n6. Gün: Van şehir merkezinde serbest zaman, meşhur Van kahvaltısı ve İstanbul'a dönüş uçuşu.",
    program_en: "Day 1: Arrival in Erzurum, Double Minaret Madrasah, Yakutiye, and authentic Cag Kebab dinner.\nDay 2: Scenic drive past Mount Ararat to Dogubayazit, explore legendary cliffside Ishak Pasha Palace.\nDay 3: Muradiye Waterfalls, Van Fortress of the Urartian Empire, and Van Cat breeding sanctuary.\nDay 4: Boat trip across Lake Van to Akdamar Island to visit the 10th-century Church of the Holy Cross.\nDay 5: Ahlat monumental Seljuk gravestones, Nemrut volcanic caldera viewpoint, and Bitlis.\nDay 6: Traditional world-renowned Van breakfast banquet, souvenir shopping, and return flight.",
    included: "• Gidiş - dönüş uçak biletleri\n• 5 gece 4 yıldızlı otellerde konaklama\n• 5 zengin kahvaltı ve 5 akşam yemeği\n• Akdamar Adası tekne turu biletleri\n• Lüks otobüslerle tüm bölge gezileri ve uzman rehberlik\n• Seyahat sağlık sigortası",
    included_en: "• Roundtrip scheduled domestic flight tickets\n• 5 nights accommodation in 4-star city hotels\n• 5 hearty breakfasts and 5 multi-course dinners\n• Akdamar Island roundtrip boat ticket\n• Luxury coach transit and specialized local tour guide\n• Comprehensive travel insurance",
    excluded: "• Tüm öğle yemekleri ve meşhur Van kahvaltısı ekstra siparişleri\n• Kişisel gümüş savat ve kilim alışverişleri\n• Müze giriş kartı harici örenyeri biletleri",
    excluded_en: "• Lunches and personal culinary additions\n• Authentic Urartian silver jewelry shopping\n• Extra museum entries not included in MüzeKart",
    departurePoints: "• 06:30 - İstanbul Havalimanı Dış Hatlar / İç Hatlar Terminali\n• 07:00 - Sabiha Gökçen Havalimanı",
    departurePoints_en: "• 06:30 AM - Istanbul Airport (IST) Domestic Terminal\n• 07:00 AM - Sabiha Gokcen Airport (SAW) Domestic Terminal",
    tourConditions: "1. Doğu Anadolu yüksek rakıma sahip olduğundan bol su tüketimi önerilir.\n2. Rahat yürüyüş ayakkabısı ve güneş gözlüğü getirilmelidir.\n3. Tur kalkışına 10 gün kalaya kadar kesintisiz iptal hakkı bulunur.",
    tourConditions_en: "1. High altitude conditions require staying hydrated during daytime excursions.\n2. Sturdy walking shoes and polarized sunglasses recommended.\n3. Full cancellation refund permitted up to 10 days before departure.",
  },
  {
    id: "tour-11",
    title: "Gelibolu Şehitlik Ziyareti",
    title_en: "Gallipoli Memorials & Historical Battlefields",
    image: "https://images.unsplash.com/photo-1601625463692-07bc1cc19515?q=80&w=800&auto=format&fit=crop",
    price: 120,
    duration: "Günübirlik Tur",
    duration_en: "Full-Day Tour",
    location: "Çanakkale, Türkiye",
    location_en: "Canakkale, Turkey",
    category: "yurt-ici",
    tag: "Kültür Turu",
    tag_en: "Historical Heritage",
    description: "Tarihin yazıldığı topraklara duygu yüklü bir yolculuk. Çanakkale Savaşları'nın yaşandığı Gelibolu Yarımadası, Şehitler Abidesi, Anzak Koyu ve Conkbayırı'nı profesyonel rehberler eşliğinde geziyoruz.",
    description_en: "A deeply moving historical pilgrimage across the Gallipoli Peninsula. Visit the Çanakkale Martyrs' Memorial, Anzac Cove, Lone Pine, and Chunuk Bair accompanied by professional expert guides.",
    program: "• 06:00: İstanbul'dan hareket ve Tekirdağ üzerinden Çanakkale Boğazı'na yolculuk.\n• 10:00: Kilitbahir Kalesi, Namazgâh Tabyası ve Seyit Onbaşı Anıtı ziyareti.\n• 12:00: Çanakkale Şehitler Abidesi ve Morto Koyu saygı ziyareti.\n• 13:30: Alçıtepe Köyü'nde geleneksel öğle yemeği molası.\n• 14:30: 57. Piyade Alayı Şehitliği, Conkbayırı, Atatürk'ün saatinin parçalandığı yer ve Anzak Koyu.\n• 18:00: 1915 Çanakkale Köprüsü üzerinden İstanbul'a dönüş ve 22:00 civarı varış.",
    program_en: "• 06:00 AM: Departure from Istanbul via Tekirdag coastal route to Dardanelles Strait.\n• 10:00 AM: Kilitbahir Fortress, Namazgah Bastions, and Corporal Seyit Memorial.\n• 12:00 PM: Monumental Çanakkale Martyrs Memorial and Morto Bay.\n• 01:30 PM: Traditional lunch stop at Alçıtepe Village.\n• 02:30 PM: 57th Infantry Regiment Memorial, Chunuk Bair trenches, and Anzac Cove.\n• 06:00 PM: Return drive via the 1915 Canakkale Suspension Bridge, arriving by 10:00 PM.",
    included: "• Lüks tur otobüsü ile gidiş - dönüş ulaşım\n• 1915 Çanakkale Köprüsü geçiş ücretleri\n• Araç içi kahvaltı paketi ve gün boyu ikramlar\n• Tarihçi ve Çanakkale uzmanı profesyonel rehberlik\n• Gelibolu Tarihi Milli Parkı tüm girişleri ve seyahat sigortası",
    included_en: "• Roundtrip luxury motorcoach transportation\n• 1915 Canakkale Bridge toll fees\n• Breakfast box and onboard hot/cold beverages\n• Specialized military historian tour guide\n• National Memorial Park entrance permits & travel insurance",
    excluded: "• Öğle yemeği ve kişisel harcamalar\n• Şehitlik hatıra objeleri ve hediyelikler",
    excluded_en: "• Lunch stop menu and personal purchases\n• Memorial souvenir objects and books",
    departurePoints: "• 05:30 - Kadıköy Evlendirme Dairesi Önü\n• 06:00 - Mecidiyeköy Torun Center Önü\n• 06:30 - Bakırköy İncirli Doğtaş Mobilya Önü\n• 07:00 - Beylikdüzü Migros Önü",
    departurePoints_en: "• 05:30 AM - Kadıköy Marriage Office Parking\n• 06:00 AM - Mecidiyeköy Torun Center Gate\n• 06:30 AM - Bakırköy İncirli Metro Station\n• 07:00 AM - Beylikdüzü Migros AVM Stop",
    tourConditions: "1. Şehitlik ziyaretlerinde saygı ve edep kurallarına uygun giyim rica olunur.\n2. Yürüyüş mesafeleri içeren bir parkur olduğundan rahat ayakkabı tercih edilmelidir.\n3. 48 saat öncesine kadar kesintisiz iptal imkanı sunulur.",
    tourConditions_en: "1. Respectful attire is requested when visiting national memorial sites and cemeteries.\n2. Tour involves moderate walking on paved trailways; flat footwear recommended.\n3. Full cancellation refund available up to 48 hours before departure.",
  },
  {
    id: "tour-12",
    title: "Günübirlik Eskişehir Turu",
    title_en: "Eskişehir Cultural Highlights & River Gondola",
    image: "https://images.unsplash.com/photo-1598889988168-98eaf8cbe8b7?q=80&w=800&auto=format&fit=crop",
    price: 90,
    duration: "Günübirlik Tur",
    duration_en: "Full-Day Tour",
    location: "Eskişehir, Türkiye",
    location_en: "Eskisehir, Turkey",
    category: "yurt-ici",
    tag: "Şehir Turu",
    tag_en: "City Explorer",
    description: "İç Anadolu'nun Venedik'i Eskişehir'i keşfedin. Odunpazarı Evleri'nin tarihi dokusu, Porsuk Çayı'nda gondol keyfi, Sazova Parkı ve Masal Şatosu ile dolu dolu bir hafta sonu kaçamağı.",
    description_en: "Discover Central Anatolia's vibrant cultural capital. Stroll through the charming pastel-hued Odunpazarı heritage quarter, enjoy a Venetian-style gondola cruise on the Porsuk River, and visit Sazova Fairytale Park.",
    program: "• 06:30: İstanbul'dan lüks otobüsümüzle hareket ve araç içi kahvaltı servisi.\n• 10:30: Sazova Bilim, Sanat ve Kültür Parkı (Masal Şatosu, Korsan Gemisi, Sabancı Uzay Evi).\n• 13:00: Odunpazarı tarihi evleri, Kurşunlu Külliyesi, Lületaşı Müzesi ve meşhur Çibörek ziyafeti.\n• 15:30: Yılmaz Büyükerşen Balmumu Heykeller Müzesi ziyareti.\n• 17:00: Porsuk Çayı Adalar bölgesinde gondol veya bot turu, serbest çay ve kahve molası.\n• 18:30: İstanbul'a dönüş yolculuğu ve 22:30 varış.",
    program_en: "• 06:30 AM: Departure from Istanbul with morning onboard breakfast box.\n• 10:30 AM: Sazova Fairytale Science & Art Park (Dream Castle, Pirate Galleon ship).\n• 01:00 PM: Odunpazari Ottoman quarter, Kursunlu Mosque complex, Meerschaum Museum, and Ciborek lunch.\n• 03:30 PM: Yılmaz Büyükerşen Wax Figures Museum.\n• 05:00 PM: Porsuk River Venetian gondola ride and cafe promenade free time.\n• 06:30 PM: Return drive to Istanbul, arriving around 10:30 PM.",
    included: "• Lüks tur aracıyla gidiş - dönüş ulaşım\n• Araç içi kahvaltı paketi ve ikramlar\n• Profesyonel kokartlı rehberlik hizmeti\n• Balmumu Müzesi giriş bileti\n• Seyahat güvence sigortası",
    included_en: "• Roundtrip luxury coach transportation\n• Onboard breakfast box and hot/cold refreshments\n• Professional Ministry licensed tour guide\n• Wax Museum fast-track entry ticket\n• Comprehensive travel accident insurance",
    excluded: "• Öğle yemeği (Çibörek menüsü) ve içecekler\n• Porsuk Çayı gondol / bot bileti\n• Kişisel lületaşı ve helva alışverişleri",
    excluded_en: "• Lunch menu and personal drinks\n• Porsuk River gondola ride ticket\n• Personal Meerschaum handicrafts and halva purchases",
    departurePoints: "• 06:00 - Bakırköy İncirli\n• 06:30 - Mecidiyeköy Torun Center\n• 07:00 - Kadıköy Evlendirme Dairesi\n• 07:30 - Kartal Köprüsü",
    departurePoints_en: "• 06:00 AM - Bakırköy İncirli Metro Station\n• 06:30 AM - Mecidiyeköy Torun Center\n• 07:00 AM - Kadıköy Marriage Office\n• 07:30 AM - Kartal Bridge Bus Stop",
    tourConditions: "1. Müzelerde sıra beklememek için grup girişleri rehber eşliğinde yapılmaktadır.\n2. Hafta sonu yoğunluk durumuna göre gondol sırası rehber tarafından planlanır.\n3. 48 saat öncesine kadar ücretsiz iptal güvencesi bulunmaktadır.",
    tourConditions_en: "1. Group entries are managed by the guide to minimize museum queue times.\n2. Gondola boarding queue is scheduled by the tour guide during promenade time.\n3. Full cancellation refund permitted up to 48 hours prior to trip.",
  },
  {
    id: "tour-13",
    title: "Büyük Balkan Turu (7 Ülke & 8 Gün)",
    title_en: "Grand Balkan Highlights & 7 Countries Tour",
    image: "https://images.unsplash.com/photo-1555990538-164741c88081?q=80&w=800&auto=format&fit=crop",
    price: 650,
    duration: "8 Günlük Tur",
    duration_en: "8-Day Tour",
    location: "Balkanlar (Bosna, Karadağ, Makedonya, Arnavutluk)",
    location_en: "Balkans (Bosnia, Montenegro, North Macedonia, Albania)",
    category: "yurt-disi",
    tag: "Kültür & Doğa",
    tag_en: "Culture & Heritage",
    description: "Saraybosna'nın Başçarşı'sından Mostar Köprüsü'ne, Kotor Körfezi'nin fiyort manzaralarından Ohrid Gölü ve Üsküp'e uzanan efsanevi vizesiz Balkan serüveni.",
    description_en: "An unforgettable visa-free voyage across the Balkans. Marvel at the historic Mostar Bridge, walk Sarajevo's Bascarsija, cruise the fjord-like Bay of Kotor, and explore UNESCO Ohrid and Skopje.",
    program: "1. Gün: İstanbul Havalimanı buluşma, Saraybosna uçuşu, Başçarşı ve Umut Tüneli gezisi.\n2. Gün: Mostar Köprüsü, Poçitel Türk Köyü ve Blagaj Alperenler Tekkesi.\n3. Gün: Karadağ'a geçiş, UNESCO korumasındaki Kotor Körfezi ve Budva tarihi şehri.\n4. Gün: Arnavutluk Tiran gezisi, İskender Bey Meydanı ve Ethem Bey Camii.\n5. Gün: Ohrid'e varış, göl kıyısında tekne turu ve St. Naum Manastırı.\n6. Gün: Manastır (Bitola), Atatürk'ün Askeri İdadisi ve Resne Sarayı.\n7. Gün: Üsküp şehir turu, Türk Çarşısı, Taş Köprü ve Vodno Dağı.\n8. Gün: Matka Kanyonu tekne gezisi ve akşam İstanbul'a dönüş uçuşu.",
    program_en: "Day 1: Flight from Istanbul to Sarajevo, Bascarsija walking tour, and Tunnel of Hope.\nDay 2: Mostar iconic bridge, Pocitelj Ottoman stone village, and Blagaj Dervish Tekke.\nDay 3: Scenic border crossing to Montenegro, UNESCO Bay of Kotor, and Budva Old Town.\nDay 4: Tirana capital tour, Skanderbeg Square, and historic Ethem Bey Mosque.\nDay 5: Arrival in Ohrid, Lake boat cruise, and Saint Naum monastery springs.\nDay 6: Bitola Military Academy of Atatürk and historic Sirok Street.\nDay 7: Skopje Stone Bridge, Old Bazaar, and Mother Teresa memorial house.\nDay 8: Matka Canyon boat expedition and return flight to Istanbul.",
    included: "• Gidiş - dönüş tarifeli uçak biletleri ve havaalanı vergileri\n• 4 yıldızlı seçkin otellerde 7 gece oda kahvaltı konaklama\n• Tüm şehir turları ve lüks otobüs transferleri\n• Profesyonel Türkçe / İngilizce kokartlı rehberlik\n• Kotor, Mostar ve Ohrid şehir giriş ücretleri\n• Uluslararası seyahat sağlık sigortası",
    included_en: "• Roundtrip international flights & airport taxes\n• 7 nights accommodation in selected 4-star hotels with breakfast\n• Luxury motorcoach transportation and cross-border transit\n• Professional English & Turkish speaking licensed guide\n• City entry taxes and historic monument permits\n• International medical travel insurance",
    excluded: "• Öğle ve akşam yemekleri (Belirtilen yöresel geceler hariç)\n• Yurtdışı çıkış harç pulu\n• Ekstra tekne turları ve kişisel harcamalar",
    excluded_en: "• Lunches and dinners (unless included in dinners)\n• International departure tax stamp\n• Optional boat cruises and personal shopping",
    departurePoints: "• 06:00 - İstanbul Havalimanı Dış Hatlar THY Kontuarı\n• 06:30 - Sabiha Gökçen Dış Hatlar Buluşma Noktası",
    departurePoints_en: "• 06:00 AM - Istanbul Airport (IST) International Terminal\n• 06:30 AM - Sabiha Gokcen Airport (SAW) International Terminal",
    tourConditions: "1. Seyahat bitiş tarihinden itibaren en az 6 ay geçerli pasaport zorunludur.\n2. Rota vizesiz ülkeleri kapsamaktadır.\n3. Tur kalkışından 30 gün öncesine kadar ücretsiz kesintisiz iptal hakkı sağlanır.",
    tourConditions_en: "1. Passport must have at least 6 months remaining validity from travel date.\n2. The tour itinerary covers visa-free destinations for Turkish citizens.\n3. 100% full cancellation refund available up to 30 days before departure.",
  },
  {
    id: "tour-14",
    title: "Klasik İtalya Turu (Roma - Floransa - Venedik)",
    title_en: "Classic Italy Heritage Tour (Rome - Florence - Venice)",
    image: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?q=80&w=800&auto=format&fit=crop",
    price: 890,
    duration: "7 Günlük Tur",
    duration_en: "7-Day Tour",
    location: "İtalya (Roma, Floransa, Venedik)",
    location_en: "Italy (Rome, Florence, Venice)",
    category: "yurt-disi",
    tag: "Sanat & Kültür",
    tag_en: "Art & Culture",
    description: "Rönesans'ın beşiği İtalya'da masalsı bir yolculuk. Roma'nın Colosseum ve Aşk Çeşmesi, Floransa'nın Duomo Meydanı ve Venedik'in gondollarla süslü kanalları.",
    description_en: "The quintessential Italian journey. Stand before the Colosseum and Trevi Fountain in Rome, admire Michelangelo's Renaissance masterworks in Florence, and glide along the romantic canals of Venice.",
    program: "1. Gün: İstanbul - Roma uçuşu, Kolezyum, Forum, Aşk Çeşmesi ve İspanyol Merdivenleri.\n2. Gün: Vatikan Şehri, San Pietro Bazilikası ve Roma serbest keşif zamanı.\n3. Gün: Toskana vadileri üzerinden Floransa'ya hareket, Duomo Katedrali ve Ponte Vecchio.\n4. Gün: Pisa Kulesi ve Siena Orta Çağ kasabası gezisi.\n5. Gün: Venedik'e varış, San Marco Meydanı ve Bazilikası, Dükler Sarayı.\n6. Gün: Venedik kanallarında gondol turu ve renkli Burano Adası ziyareti.\n7. Gün: Milano Duomo Meydanı serbest zaman ve akşam İstanbul'a dönüş uçuşu.",
    program_en: "Day 1: Flight from Istanbul to Rome, Colosseum, Roman Forum, Trevi Fountain, and Spanish Steps.\nDay 2: Vatican City, St. Peter's Basilica, and Rome cultural promenade.\nDay 3: Scenic Tuscan drive to Florence, Santa Maria del Fiore Cathedral, and Ponte Vecchio.\nDay 4: Leaning Tower of Pisa and medieval Siena excursion.\nDay 5: Transfer to Venice, St. Mark's Square and Basilica, Doge's Palace.\nDay 6: Romantic Venetian gondola ride and colorful Burano fishermen island.\nDay 7: Milan Galleria & Duomo Square shopping, transfer to Malpensa for return flight.",
    included: "• Türk Hava Yolları gidiş - dönüş tarifeli uçak biletleri\n• 4 yıldızlı otellerde 6 gece oda & kahvaltı konaklama\n• Şehirlerarası lüks otobüs ve hızlı tren transferleri\n• Profesyonel Türkçe rehberlik hizmeti\n• Venedik Vaporetto tekne geçiş ücretleri\n• Uluslararası Schengen kapsamlı seyahat sigortası",
    included_en: "• Roundtrip scheduled flights with Turkish Airlines\n• 6 nights in 4-star hotels with breakfast\n• Luxury coach transit and high-speed rail connections\n• Professional licensed English & Turkish guide\n• Venice Vaporetto water taxi ferry transfers\n• Full Schengen travel health insurance policy",
    excluded: "• İtalya vize ve servis ücreti\n• İtalya şehir konaklama turist vergileri (otel ödemeli)\n• Kişisel harcamalar ve müze giriş biletleri",
    excluded_en: "• Schengen visa application and processing fee\n• Local Italian municipal city tourist taxes\n• Museum entries and personal shopping",
    departurePoints: "• 05:30 - İstanbul Havalimanı Dış Hatlar THY Kontuarı",
    departurePoints_en: "• 05:30 AM - Istanbul Airport (IST) International Departures Hall",
    tourConditions: "1. Seyahat için geçerli Schengen vizesi veya yeşil pasaport gereklidir.\n2. Pasaport geçerlilik süresi seyahat bitişinden itibaren en az 90 gün olmalıdır.\n3. 30 gün öncesine kadar ücretsiz iptal güvencesi sunulmaktadır.",
    tourConditions_en: "1. Valid Schengen visa or visa-free passport required for entry into Italy.\n2. Passport must have minimum 90 days validity beyond departure date.\n3. Free cancellation guaranteed up to 30 days before departure.",
  }
];

export const HOTELS_DATA: Hotel[] = [
  {
    id: "hotel-1",
    title: "Manila Lüks Otel",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop",
    price: 200,
    location: "Manila, Filipinler",
    stars: 5,
    showers: 2,
    beds: 3,
    tag: "Şehir Merkezinde",
    description: "Manila'nın kalbinde, birinci sınıf lüksü, tarihi miras süitleri ve ödüllü çok sayıda restoranı ile ikonik bir otel.",
  },
  {
    id: "hotel-2",
    title: "Banff Alpin Dağ Evi",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=800&auto=format&fit=crop",
    price: 250,
    location: "Banff, Alberta, Kanada",
    stars: 5,
    showers: 2,
    beds: 2,
    tag: "Dağ Eteğinde",
    description: "Karla kaplı dağ zirveleriyle çevrili bu sıcacık ahşap dağ evi; rustik zarafet, şömineli süitler ve açık havada birinci sınıf bir spa sunmaktadır.",
  },
  {
    id: "hotel-3",
    title: "Phuket Sahil Resort",
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop",
    price: 180,
    location: "Phuket, Tayland",
    stars: 4,
    showers: 1,
    beds: 2,
    tag: "Deniz Manzaralı",
    description: "Özel kumsalı, sonsuzluk havuzları ve egzotik lezzetler sunan sahil restoranları ile dinlendirici bir tropikal kaçış noktası.",
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "blog-1",
    title: "Balkan Seyahatine Çıkacakların Bilmesi Gereken 7 İpucu",
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=800&auto=format&fit=crop",
    date: "14 Mart 2025",
    author: "Cesur Akgün",
    summary: "Balkanların eşsiz kültürünü, lezzetlerini ve doğasını keşfetmeden önce bavulunuzda ve aklınızda bulunması gerekenler.",
    content: "Balkanlar, sıcakkanlı insanları, zengin tarihi ve nefes kesen doğal manzaralarıyla son yılların en popüler rotalarından biri. Üsküp'ten Ohrid'e uzanan yolculuklarda hem vizesiz seyahat konforu yaşayabilir hem de Osmanlı mirasıyla yoğrulmuş şehirlerde kendinizi evinizde hissedebilirsiniz.",
    category: "Gezi Rehberi",
    comments: [
      {
        id: "c-1",
        name: "Mehmet Demir",
        email: "mehmet@example.com",
        date: "15 Mart 2025",
        content: "Ohrid Gölü kenarındaki alabalık deneyimi gerçekten anlatıldığı kadar harika mı? Çok faydalı bir yazı olmuş, teşekkürler.",
      },
    ],
  },
  {
    id: "blog-2",
    title: "Kapadokya'da Balon Turu: Gökyüzünde Gün Doğumu Deneyimi",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop",
    date: "10 Mart 2025",
    author: "Zeynep Kaya",
    summary: "Peri bacalarının üzerinde süzülürken sabahın ilk ışıklarını izlemenin büyüsü ve dikkat edilmesi gerekenler.",
    content: "Kapadokya, dünyanın en etkileyici jeolojik oluşumlarına ev sahipliği yapıyor. Sabahın erken saatlerinde rüzgarın sakin olduğu anlarda gökyüzüne yükselen yüzlerce rengarenk sıcak hava balonu, hem havadan hem de karadan seyri doyumsuz bir görsel şölen sunuyor.",
    category: "Macera",
    comments: [],
  },
  {
    id: "blog-3",
    title: "Doğu Ekspresi ile Büyüleyici Kış Masalı",
    image: "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=80&w=800&auto=format&fit=crop",
    date: "02 Mart 2025",
    author: "Caner Öztürk",
    summary: "Ankara'dan Kars'a uzanan raylarda karlar altındaki Anadolu manzaraları ve unutulmaz anılar.",
    content: "Doğu Ekspresi yolculuğu sadece bir tren seyahati değil, aynı zamanda nostaljik bir kültür gezisidir. İliç, Erzincan ve Erzurum duraklarında yerel tatları denerken, tren pencerelerinden akıp giden karlı dağlar size huzur verir.",
    category: "İpuçları",
    comments: [],
  },
];

export const TESTIMONIALS = [
  {
    id: "test-1",
    name: "Murat Şen",
    position: "Gezgin & Blogger",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150&auto=format&fit=crop",
    stars: 5,
    text: "Makedonya ve Ohrid turu hayatımın en keyifli seyahatlerinden biriydi. Rehberin ilgisi, seçilen oteller ve güzergahın akıcılığı kusursuzdu. Teşekkürler Cesur Akgün!",
  },
  {
    id: "test-2",
    name: "Ayşe Özkan",
    position: "Öğretmen",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&auto=format&fit=crop",
    stars: 5,
    text: "Kapadokya turumuz rüya gibi geçti. Sabah balona binmek ve gün doğumunu izlemek inanılmazdı. Her şey saat gibi işledi, kesinlikle tekrar tercih edeceğim.",
  },
  {
    id: "test-3",
    name: "Cihan Yılmaz",
    position: "Doğa Fotoğrafçısı",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&auto=format&fit=crop",
    stars: 5,
    text: "Karadeniz Batum turundaki yayla rotaları ve fotoğraf molaları tam bir doğa aşığı için biçilmiş kaftandı. Profesyonellik ve samimiyet bir aradaydı.",
  },
];

export const DEFAULT_SITE_CONTENT: SiteContent = {
  hero: {
    badge: "Dünyayı Keşfedin",
    badge_en: "Explore the World",
    title: "En Beğendiğiniz Yerleri Bizimle Keşfedin",
    title_en: "Discover Your Favorite Destinations With Us",
    subtitle: "Gereksiz detaylarla uğraşmadan, dünyanın her köşesine kolayca seyahat edin.",
    subtitle_en: "Travel effortlessly to every corner of the world without worrying about the details.",
    backgroundImage: "https://images.unsplash.com/photo-1506929562872-bb421503ef21?q=80&w=1920&auto=format&fit=crop",
    backgroundImages: [
      "https://images.unsplash.com/photo-1506929562872-bb421503ef21?q=80&w=1920&auto=format&fit=crop", // Tropical Paradise
      "https://images.unsplash.com/photo-1641128324972-af3212f0f6bd?q=80&w=1920&auto=format&fit=crop", // Cappadocia Hot Air Balloons Sunrise
      "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?q=80&w=1920&auto=format&fit=crop", // Istanbul Bosphorus Sunset
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1920&auto=format&fit=crop", // Aegean Turquoise Coast
      "https://images.unsplash.com/photo-1520114008272-38eb7636e788?q=80&w=1920&auto=format&fit=crop"  // Black Sea Highlands
    ],
    autoplayInterval: 6000,
  },
  about: {
    badge: "Cesur Akgün'e Hoş Geldiniz",
    badge_en: "Welcome to Cesur Akgün",
    title: "Hayalinizdeki Seyahat Rezervasyonlarını Güvenle Yönetiyoruz",
    title_en: "Seamlessly Managing Your Dream Travel Bookings",
    paragraph1: "15 yılı aşkın sektör deneyimiyle Cesur Akgün Travel Agency, macera, kültürel keşif ve birinci sınıf lüks misafirperverliği birleştiren seyahat programları sunmaya kendini adamıştır.",
    paragraph1_en: "With over 15 years of industry experience, Cesur Akgün Travel Agency is dedicated to curating travel itineraries that blend adventure, cultural exploration, and premium hospitality.",
    paragraph2: "Profesyonel ekibimiz, ülkemizin dört bir yanındaki eşsiz güzellikleri ve seçkin yurtdışı rotalarını keşfetmeniz için kusursuz deneyimler düzenlemek üzere çalışmaktadır. Tarihi dokuya sahip kültürel gezilerden doğa ile iç içe maceralara kadar her detayı sizin için özenle planlıyoruz.",
    paragraph2_en: "Our expert team crafts unforgettable journeys across Turkey's hidden gems and premier international destinations, ensuring meticulous attention to detail from historical tours to breathtaking outdoor expeditions.",
    happyTravelers: "3.200+",
    experienceYears: "15+",
    image: "https://images.unsplash.com/photo-1522163182402-834f871fd851?q=80&w=800&auto=format&fit=crop",
  },
  contact: {
    address: "Hüseyinağa Mh. İstiklal Cd. Sahne Sk. No:1 Kat:4 D:405 Beyoğlu / İstanbul",
    address_en: "Hüseyinağa Dist. Istiklal Ave. Sahne St. No:1 Fl:4 Beyoglu / Istanbul, Turkey",
    phone1: "0544 950 84 85",
    phone2: "0507 364 24 18",
    phone3: "0850 259 41 42",
    email: "info@cesurakguntravel.com",
    tursabNo: "13732",
    companyName: "Cesur Temur Akgün Seyahat Acentası Tic. Ltd. Şti",
  },
};
